#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wavpack
Version  : 5.5.0
Release  : 11
URL      : https://www.wavpack.com/wavpack-5.5.0.tar.xz
Source0  : https://www.wavpack.com/wavpack-5.5.0.tar.xz
Summary  : wavpack library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: wavpack-bin = %{version}-%{release}
Requires: wavpack-lib = %{version}-%{release}
Requires: wavpack-license = %{version}-%{release}
Requires: wavpack-man = %{version}-%{release}
BuildRequires : libxml2-dev

%description
<img src="http://www.rarewares.org/wavpack/logos/wavpacklogo.png" width="250"></img>

%package bin
Summary: bin components for the wavpack package.
Group: Binaries
Requires: wavpack-license = %{version}-%{release}

%description bin
bin components for the wavpack package.


%package dev
Summary: dev components for the wavpack package.
Group: Development
Requires: wavpack-lib = %{version}-%{release}
Requires: wavpack-bin = %{version}-%{release}
Provides: wavpack-devel = %{version}-%{release}
Requires: wavpack = %{version}-%{release}

%description dev
dev components for the wavpack package.


%package doc
Summary: doc components for the wavpack package.
Group: Documentation
Requires: wavpack-man = %{version}-%{release}

%description doc
doc components for the wavpack package.


%package lib
Summary: lib components for the wavpack package.
Group: Libraries
Requires: wavpack-license = %{version}-%{release}

%description lib
lib components for the wavpack package.


%package license
Summary: license components for the wavpack package.
Group: Default

%description license
license components for the wavpack package.


%package man
Summary: man components for the wavpack package.
Group: Default

%description man
man components for the wavpack package.


%prep
%setup -q -n wavpack-5.5.0
cd %{_builddir}/wavpack-5.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664896517
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1664896517
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wavpack
cp %{_builddir}/wavpack-%{version}/COPYING %{buildroot}/usr/share/package-licenses/wavpack/c346a1628532ec3a23739bbbd203b8420a79fc6e || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wavpack
/usr/bin/wvgain
/usr/bin/wvtag
/usr/bin/wvunpack

%files dev
%defattr(-,root,root,-)
/usr/include/wavpack/wavpack.h
/usr/lib64/libwavpack.so
/usr/lib64/pkgconfig/wavpack.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/wavpack/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwavpack.so.1
/usr/lib64/libwavpack.so.1.2.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wavpack/c346a1628532ec3a23739bbbd203b8420a79fc6e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/wavpack.1
/usr/share/man/man1/wvgain.1
/usr/share/man/man1/wvtag.1
/usr/share/man/man1/wvunpack.1
