#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wavpack
Version  : 5.1.0
Release  : 3
URL      : http://wavpack.com/wavpack-5.1.0.tar.bz2
Source0  : http://wavpack.com/wavpack-5.1.0.tar.bz2
Summary  : wavpack library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: wavpack-bin = %{version}-%{release}
Requires: wavpack-lib = %{version}-%{release}
Requires: wavpack-license = %{version}-%{release}
Requires: wavpack-man = %{version}-%{release}
Patch1: CVE-2018-6767.patch
Patch2: CVE-2018-7253.patch
Patch3: CVE-2018-7254.patch
Patch4: CVE-2018-10536.patch
Patch5: CVE-2018-10538.patch

%description
////////////////////////////////////////////////////////////////////////////
//                           **** WAVPACK ****                            //
//                  Hybrid Lossless Wavefile Compressor                   //
//                          All Rights Reserved.                          //
//      Distributed under the BSD Software License (see license.txt)      //
////////////////////////////////////////////////////////////////////////////

%package bin
Summary: bin components for the wavpack package.
Group: Binaries
Requires: wavpack-license = %{version}-%{release}
Requires: wavpack-man = %{version}-%{release}

%description bin
bin components for the wavpack package.


%package dev
Summary: dev components for the wavpack package.
Group: Development
Requires: wavpack-lib = %{version}-%{release}
Requires: wavpack-bin = %{version}-%{release}
Provides: wavpack-devel = %{version}-%{release}

%description dev
dev components for the wavpack package.


%package lib
Summary: lib components for the wavpack package.
Group: Libraries
Requires: wavpack-license = %{version}-%{release}

%description lib
lib components for the wavpack package.


%package license
Summary: license components for the wavpack package.
Group: Default

%description license
license components for the wavpack package.


%package man
Summary: man components for the wavpack package.
Group: Default

%description man
man components for the wavpack package.


%prep
%setup -q -n wavpack-5.1.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551414912
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1551414912
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wavpack
cp COPYING %{buildroot}/usr/share/package-licenses/wavpack/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wavpack
/usr/bin/wvgain
/usr/bin/wvtag
/usr/bin/wvunpack

%files dev
%defattr(-,root,root,-)
/usr/include/wavpack/wavpack.h
/usr/lib64/libwavpack.so
/usr/lib64/pkgconfig/wavpack.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwavpack.so.1
/usr/lib64/libwavpack.so.1.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wavpack/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/wavpack.1
/usr/share/man/man1/wvgain.1
/usr/share/man/man1/wvtag.1
/usr/share/man/man1/wvunpack.1
