#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : wavpack
Version  : 5.8.1
Release  : 14
URL      : https://www.wavpack.com/wavpack-5.8.1.tar.bz2
Source0  : https://www.wavpack.com/wavpack-5.8.1.tar.bz2
Summary  : wavpack library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: wavpack-bin = %{version}-%{release}
Requires: wavpack-lib = %{version}-%{release}
Requires: wavpack-man = %{version}-%{release}
BuildRequires : buildreq-configure
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<img src="https://www.wavpack.com/logos/wavpacklogo-with-theme.svg" width="250"></img>

%package bin
Summary: bin components for the wavpack package.
Group: Binaries

%description bin
bin components for the wavpack package.


%package dev
Summary: dev components for the wavpack package.
Group: Development
Requires: wavpack-lib = %{version}-%{release}
Requires: wavpack-bin = %{version}-%{release}
Provides: wavpack-devel = %{version}-%{release}
Requires: wavpack = %{version}-%{release}

%description dev
dev components for the wavpack package.


%package doc
Summary: doc components for the wavpack package.
Group: Documentation
Requires: wavpack-man = %{version}-%{release}

%description doc
doc components for the wavpack package.


%package lib
Summary: lib components for the wavpack package.
Group: Libraries

%description lib
lib components for the wavpack package.


%package man
Summary: man components for the wavpack package.
Group: Default

%description man
man components for the wavpack package.


%prep
%setup -q -n wavpack-5.8.1
cd %{_builddir}/wavpack-5.8.1
pushd ..
cp -a wavpack-5.8.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738104580
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738104580
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/wavpack
/V3/usr/bin/wvgain
/V3/usr/bin/wvtag
/V3/usr/bin/wvunpack
/usr/bin/wavpack
/usr/bin/wvgain
/usr/bin/wvtag
/usr/bin/wvunpack

%files dev
%defattr(-,root,root,-)
/usr/include/wavpack/wavpack.h
/usr/lib64/libwavpack.so
/usr/lib64/pkgconfig/wavpack.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/wavpack/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libwavpack.so.1.2.7
/usr/lib64/libwavpack.so.1
/usr/lib64/libwavpack.so.1.2.7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/wavpack.1
/usr/share/man/man1/wvgain.1
/usr/share/man/man1/wvtag.1
/usr/share/man/man1/wvunpack.1
